[dependencies]
circt_opt = "../../circt/build/bin/circt-opt"
mlir_opt = "../../circt/build/bin/mlir-opt"
verilator = "../../circt/ext/bin/verilator"
cxx = "/usr/bin/g++"

[[test]]
top = 'gesummv'
test_file = '../../tests/gesummv/tb_gesummv.py'
hir_file = '../../tests/gesummv/gesummv.mlir'
